### PR TITLE
Check SMS delivery status 

### LINKED ISSUE #361: Add check to SMS sending function
When sending SMS, we get a success message if the POST request to `gatewayapi` was successful, but fails silently if there is an issue provider side (insufficient funds, non-whitelisted URL, etc.) We should add a check to see if the message was `ACCEPTED` or `DELIVERED` and return success/error based on that state.

### PR DESCRIPTION
**Pull request by ikusteu**
Fixes #361

### CODE REVIEW

**Review by silviot — APPROVED** [review]

File: eisbuk-admin/functions/src/https.ts [hunk 1]
```diff
@@ -61,104 +59,127 @@ export const sendEmail = functions
...
+          SendSMSErrors.SendingFailed,
+          res
+        );
+      }
+
+      const smsId = res.ids[0];
+
+      const [smsOk, status, errorMessage] = await pRetry(
+        () => checkSMS(smsId, authToken),
+        { maxRetryTime: 5000 }
```
Comment (silviot) [inline eisbuk-admin/functions/src/https.ts:131]: I think we should use something else to achieve our goals.

Our goal is to make sure that, no matter what, our function will return in less than X seconds. Imagine, for instance, that the remote service is taking 60 seconds to process requests.

`maxRetryTime` [comes into play when it's time to retry something](https://github.com/tim-kos/node-retry/commit/339a30a8b957a88cd68a8e14bbcf7462b340b4ea). So in the example above, if the remote service always takes 60 seconds, this invocation will take 60 seconds, and not retry a second time (since we exceeded the five seconds allowance `maxRetryTime` gave us.

I think we need something like [`p-timeout`](https://www.npmjs.com/package/p-timeout) and/or the firebase [`timeoutSeconds`](https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation) option to pass to `runWith`.
