### PR TITLE
Fix/query auth status

### LINKED ISSUE #930: `queryAuthStatus` and `queryAuthStatus2` are leaking user secret keys
Given a user email or phone, an anonymous user can query these functions to get their secret key(s). The functions should check that the `authString` provided in the request matches the currently logged in used, and return `{"result":{"isAdmin":false,"secretKeys":[]}}` if they don't.

`authString` needs to be removed from `QueryAuthStatusPayload`. The authentication string needs to be pulled from the functions context, [as documented here](https://firebase.google.com/docs/functions/callable?gen=1st) in a similar way to [what we already do in other cloud functions](https://github.com/eisbuk/EisBuk/blob/0182d86e4d57f7ea2dc44547ec7d70fe1c638894/packages/functions/src/checks/https.ts#L30).

### PR DESCRIPTION
**Pull request by ikusteu**
Fixes #930

### CODE REVIEW

File: packages/functions/src/auth.ts [hunk 1]
```diff
@@ -85,12 +26,21 @@ export const queryAuthStatus2 = functions
...
+      "queryAuthStatus",
+      async (
+        payload: QueryAuthStatusPayload,
+        { auth }
+      ): Promise<AuthStatus> => {
+        // Organization is required to even start the functionality
+        checkRequiredFields(payload, ["organization"]);
+        const { organization } = payload;
+
+        await checkUser(organization, auth);
```
Comment (silviot) [inline packages/functions/src/auth.ts:38]: `checkUser` has no side effects AFAICT.
This invocation can probably be removed.

File: packages/client/src/__tests__/auth.test.ts [hunk 2]
```diff
@@ -2,103 +2,59 @@
...
+import { signInEmail } from "@/__testUtils__/auth";
 
 describe("Test authentication", () => {
+  afterEach(() => {
+    auth.signOut();
+  });
+
   describe("Test queryAuthStatus", () => {
-    const queryAuthStatus = (organization: string, authString: string) =>
+    const queryAuthStatus = (organization: string) =>
```
Comment (silviot) [inline packages/client/src/__tests__/auth.test.ts:31]: We should probably [also change the invocation](https://github.com/eisbuk/EisBuk/blob/711f4120955f0677096a8b1957f3fee3cf9f3510/packages/client/src/store/actions/authOperations.ts#L67) of this cloud function to omit `authString` for consistency.

File: packages/shared/src/types/cloudFunctions.ts [hunk 3]
```diff
@@ -27,8 +27,6 @@ export type CreateAuthUserPayload = Partial<{
 export interface QueryAuthStatusPayload {
   /** Current organization */
   organization: string;
-  /** String used to authenticate user, either email or phone */
-  authString: string;
```
Comment (silviot) [inline packages/shared/src/types/cloudFunctions.ts:31]: We should probably [also change the invocation](https://github.com/eisbuk/EisBuk/blob/711f4120955f0677096a8b1957f3fee3cf9f3510/packages/client/src/store/actions/authOperations.ts#L67) of this cloud function to omit `authString` for consistency.

**Review by silviot — APPROVED** [review]
I left a couple of comments about things that can be improved, but they're not really blockers. I'm opening a new ticket about using firestore indices. The small fixes can be done in that context too.
