### PR TITLE
Polish Functions Fixes: #117

### LINKED ISSUE #117: Polish functions
This is part of codebase rewrites related to functions, shouldn't be too big of a task, it mainly focuses on readability, organization and documentation, the tasks are self explanatory: 

- [x] Rewrite certain functions for readability: 
- Convert promises to async-await (only occurs in test utils which is a retry function and will be replaced with p-retry)
- Reduce the conditionals to ternary/switch (make the decision on the spot)

- [x] Add JSDoc to all of the functions:
- Remove `require-jsdoc: "off"` from `.eslintrc.js`
- Use the said es-lint rule to locate functions needing JSDoc

- [ ] Add more definitive typing of cloud functions and apply to `invokeFunction()` on the client app (I will do that one)
- [x] Convert all to arrow syntax
- [x] Avoid inline function declaration in JSX components (makes components a bit more pure)

### PR DESCRIPTION
**Pull request by fadwamahmoud**
Fixes #117 
- Functions are more readable 
- JSDocs are added to functions missing docs
- p-retry library is implemented for retry functionality

### CODE REVIEW

File: eisbuk-admin/src/AppContent.tsx [hunk 1]
```diff
@@ -38,7 +38,7 @@ import { queryUserAdminStatus } from "@/store/actions/actions";
  * General components to be returned from the AppContent, regardless of auth status
  * @returns
  */
-function AppComponents() {
```
Comment (ikusteu) [inline eisbuk-admin/src/AppContent.tsx:41]: This should be typed as `React.FC`

**Review by ikusteu — CHANGES_REQUESTED** [review]
I've created a PR to include some updates into this branch

**Review by ikusteu — APPROVED** [review]
